apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "Team4KeyVaultMoJ"
    objects: |
      array:
        - |
          objectName: SQL-USER              
          objectType: secret
          objectVersion: ""
          objectAlias: SQL_USER
        - |
          objectName: SQL-PASSWORD              
          objectType: secret
          objectVersion: ""
          objectAlias: SQL_PASSWORD
    tenantId: "b40dc1a2-7266-4225-8c82-99ef76fb714b"
