apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
      tier: backend
  template:
    metadata:
      labels:
        app: user
        tier: backend
    spec:
      containers:
      - name: user
        image: registryzyo9157.azurecr.io/userprofile:latest
        ports:
        - containerPort: 80
        env:
          - name: SQL_USER
            value: sqladminzYo9157
          - name: SQL_PASSWORD
            value: cW1zk2Ev4
          - name: SQL_DBNAME
            value: mydrivingDB
          - name: SQL_SERVER
            value: sqlserverzyo9157.database.windows.net
          - name: ASPNETCORE_ENVIRONMENT
            value: Local         
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
          